version: '2'

services:

  keycloak:
    image: jboss/keycloak:3.4.3.Final
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    ports:
      - 8180:8080
    networks:
      - sso

  # username: elastic
  # password: changeme
  elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:5.6.5
      container_name: elasticsearch
      environment:
        - cluster.name=docker-cluster
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      ulimits:
        memlock:
          soft: -1
          hard: -1
      mem_limit: 1g
      volumes:
        - esdata:/usr/share/elasticsearch/data
      ports:
        - 9200:9200
      networks:
        - elk

volumes:
  esdata:
    driver: local

networks:
  sso:
  elk: